NullPointerException: Cannot invoke "String.equals(Object)" because the
[#182026669]

Removed unnecessary code from FilenameGenerator.java and
FilenameGeneratorTest.java

Co-authored-by: Chibuisi Enyia <cenyia@codeforamerica.org>
Co-authored-by: Eric M Johnson <eric.m.johnson@state.mn.us>