NullPointerException: Cannot invoke "String.equals(Object)" because the
[#182026669]

Refactor if Condition in ApplicationStatusRepository.java.

This story contains bug resolved for
1. Nullpointer exception caused due to fail to add the cover page to te
pdf.
2. Extra row added in application_status table if an application has
more than one routing destination.

Co-authored-by: Chibuisi Enyia <cenyia@codeforamerica.org>
Co-authored-by: Eric M Johnson <eric.m.johnson@state.mn.us>