Blank status (#795)
NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.apache.pdfbox.pdmodel.inte...

[#182026669]

Co-authored-by: Eric M Johnson <eric.m.johnson@state.mn.us>